[package]
name = "steviegoodman/waiter"
description = "Have your Roblox hierarchy instances served to you with convenience!"
version = "2.0.8"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.toml"]

[dependencies]
TableUtil = "sleitnick/table-util@1.2.0"